import Head from 'next/head'
import Image from 'next/image'
import { useState, useRef } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [days, setDays] = useState(0);
  const dateFrom = useRef(new Date());
  const dateTo = useRef(new Date());
  const [toggle, setToggle] = useState(false);
  const calculateDays = () => {
    if (dateTo.current.value !== "") {
      console.log(dateTo.current.value === "")
      var aFecha2 = dateFrom.current.value.split('-');
      var aFecha1 = dateTo.current.value.split('-');
      var fFecha1 = Date.UTC(aFecha1[0], aFecha1[1] - 1, aFecha1[2]);
      var fFecha2 = Date.UTC(aFecha1[0], aFecha1[1] - 1, aFecha1[2]);
      var dif = fFecha2 - fFecha1;
      var dias = Math.floor(dif / (1000 * 60 * 60 * 24));
      console.log("fecha desde:", dateFrom.current.value);
      console.log("fecha to:", dateTo.current.value)

      var fFecha1 = Date.UTC(aFecha1[0], aFecha1[1] - 1, aFecha1[2]);
      var fFecha2 = Date.UTC(aFecha2[0], aFecha2[1] - 1, aFecha2[2]);
      var dif = fFecha2 - fFecha1;
      var dias = Math.floor(dif / (1000 * 60 * 60 * 24));
      if (dias > 0) {
        setToggle(true);
        setDays(dias);
      } else {
        setToggle(false);
        setDays(-1 * dias);
      }
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/gsawhite.png" height="200px" alt="" />
        <h1 className={styles.title}>
          Days Between Dates Calculator
        </h1>

        <p className={styles.description}>
          Get started by adding {' '}
           2 different dates 
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>

            From

            <input className={styles.dateInput} type="date" id="start"
              onChange={calculateDays}
              ref={dateFrom}
              name="trip-start"
              min="2018-01-01" ></input>
          </div>
          <div className={styles.card}>

            To

            <input className={styles.dateInput} type="date" id="start" name="trip-start"
              onChange={calculateDays}
              ref={dateTo}
              min="2018-01-01" />
          </div>
        </div>
        <div className={styles.card}>
          <h4>Days between dates:
            <code className={styles.code} >
              {days}
            </code>
          </h4>
        </div>
        <h3>{
          toggle ? "Note: Date From is before Date to" : ""}
        </h3>






      </main >

      <footer className={styles.footer}>
        Powered by{' '}
        <span>
          Gsa Team
       </span>
      </footer>
    </div >
  )
}
